export interface TilordnetSaksbehandlerDto {
    navIdent: string;
    fornavn: string;
    etternavn: string;
    tilordnetSaksbehandlerPåOppgave: TilordnetSaksbehandlerPåOppgave;
}

export enum TilordnetSaksbehandlerPåOppgave {
    IKKE_SATT = 'IKKE_SATT',
    INNLOGGET_SAKSBEHANDLER = 'INNLOGGET_SAKSBEHANDLER',
    ANNEN_SAKSBEHANDLER = 'ANNEN_SAKSBEHANDLER',
    OPPGAVE_FINNES_IKKE = 'OPPGAVE_FINNES_IKKE',
    OPPGAVE_FINNES_IKKE_SANNSYNLIGVIS_INNLOGGET_SAKSBEHANDLER = 'OPPGAVE_FINNES_IKKE_SANNSYNLIGVIS_INNLOGGET_SAKSBEHANDLER',
    OPPGAVE_TILHØRER_IKKE_TILLEGGSSTONADER = 'OPPGAVE_TILHØRER_IKKE_TILLEGGSSTONADER',
    UTVIKLER_MED_VEILDERROLLE = 'UTVIKLER_MED_VEILDERROLLE',
}
