#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n tilleggsstonader get secret azuread-tilleggsstonader-sak-frontend-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: tilleggsstonader-sak-frontend-lokal
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  secretName: azuread-tilleggsstonader-sak-frontend-lokal
  logoutUrl: "http://localhost:3000"
  tenant: trygdeetaten.no
  replyUrls:
    - url: "http://localhost:3000/oauth2/callback"
  claims:
    extra:
      - "NAVident"
    groups:
      - id: "3611981f-eda7-46ab-b8f2-50c3159e101c" # 0000-GA-Tilleggsstonader-Veileder
      - id: "31a99292-9461-40bf-b2d0-a815697dfbb4" # 0000-GA-Tilleggsstonader-Saksbehandler
      - id: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424" # 0000-GA-Tilleggsstonader-Beslutter
      - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
      - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
      - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
      - id: "d5f850f4-90b7-41c1-a460-7ccca4bb171d" # 0000-GA-ENHET_4402 - Håndterer utlandssaker
      - id: "e9696ba8-0572-4556-ab78-d8605cb6b0bf" # 0000-GA-ENHET_4462 - NAY Tilleggsstønader
      - id: "a2a98575-4ef8-4244-ab3e-2d74de3db5bf" # 0000-GA-ENHET_0387 - NAV Tiltak Oslo (Tiltaksenheten)