apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tilleggsstonader-sak-frontend"
  namespace: "tilleggsstonader"
  labels:
    "team": "tilleggsstonader"

spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://tilleggsstonader.intern.dev.nav.no"
  azure:
    application:
      enabled: true