apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tilleggsstonader-sak-frontend"
  namespace: "tilleggsstonader"
  labels:
    "team": "tilleggsstonader"

spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    initialDelay: 20
    timeout: 60
  port: 3000
  readiness:
    path: "/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://tilleggsstonader.intern.dev.nav.no"
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      replyURLs:
        - "https://tilleggsstonader.intern.dev.nav.no/oauth2/callback"
        - "https://localhost:3000/oauth2/callback"
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "3611981f-eda7-46ab-b8f2-50c3159e101c" # 0000-GA-Tilleggsstonader-Veileder
          - id: "31a99292-9461-40bf-b2d0-a815697dfbb4" # 0000-GA-Tilleggsstonader-Saksbehandler
          - id: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424" # 0000-GA-Tilleggsstonader-Beslutter
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
  env:
    - name: ENV
      value: preprod