apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tilleggsstonader-sak-frontend"
  namespace: "tilleggsstonader"
  labels:
    "team": "tilleggsstonader"

spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    initialDelay: 20
    timeout: 60
  port: 3000
  readiness:
    path: "/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://tilleggsstonader.intern.nav.no"
  accessPolicy:
    outbound:
      rules:
        - application: tilleggsstonader-sak
        - application: tilleggsstonader-klage
        - application: familie-endringslogg
          namespace: teamfamilie
      external:
        - host: tilleggsstonader-unleash-api.nav.cloud.nais.io
        - host: modiacontextholder.intern.nav.no
  azure:
    sidecar:
      enabled: true
      autoLogin: false
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "0f841c83-0d64-407c-80d5-4eb51dfaee1e" # 0000-GA-Tilleggsstonader-Veileder
          - id: "c1e9edec-0c10-4df2-8c74-324ab9922220" # 0000-GA-Tilleggsstonader-Saksbehandler
          - id: "224b5097-d0af-462c-8d8e-49c0e8a42661" # 0000-GA-Tilleggsstonader-Beslutter
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # 0000-GA-Fortrolig_Adresse
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" # 0000-GA-Egne_ansatte
          - id: "71f94b2e-5c60-4f55-9db8-ce0235f4d5b8" # 0000-GA-ENHET_4402 - Håndterer utlandssaker
  envFrom:
    - secret: tilleggsstonader-sak-frontend-unleash-api-token
  env:
    - name: ENV
      value: prod