apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tilleggsstonader-sak-frontend
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: tilleggsstonader
  secretName: tilleggsstonader-sak-frontend-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: production
  type: FRONTEND