name: Deploy unleash api-token for prod

on:
  workflow_dispatch:

permissions:
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: deploy unleash api-token
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash-apitoken-prod.yaml
          PRINT_PAYLOAD: true