name: Deploy unleash api-token for prod

on:
  workflow_dispatch:

permissions:
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: deploy unleash api-token
        uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash-apitoken-prod.yaml
          PRINT_PAYLOAD: true