name: Deploy unleash api-token for dev

on:
  workflow_dispatch:

permissions:
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: deploy unleash api-token
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash-apitoken-preprod.yaml
          PRINT_PAYLOAD: true