name: Deploy unleash api-token for prod

on:
  workflow_dispatch:

permissions:
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: deploy unleash api-token
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash-apitoken-prod.yaml
          PRINT_PAYLOAD: true