name: Deploy unleash api-token for dev

on:
  workflow_dispatch:

permissions:
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: deploy unleash api-token
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash-apitoken-preprod.yaml
          PRINT_PAYLOAD: true